### ISSUE TITLE
Input Dimension Error

### ISSUE THREAD

**Issue by Gevorg-Minasyan** [ChenglongChen/tensorflow-DeepFM#13]
Hello,

In your paper, it is written that "the lengths of different input field vectors can be different" which means the input data Xi can contain lists of different lengths. I have tried to run the code with the latter, but it gave the following error "ValueError: setting an array element with a sequence.". Can you please suggest what to do?

Thanks in advance

**Comment by ChenglongChen** [comment]
1. To be clear, this is an un-official implementation of the DeepFM presented in the paper, and I am not the author :)
2. I do not quite understand what you mean by "the lengths of different input field vectors can be different". I have three understandings. 
2.1 First, each feature field can have different size of features. For example, while age filed can have roughly 100 unique feature values to take from, ad ids can take thousands or million values. However, when it comes to DeepFM, in both case, you can use just one feature index to represent this feature field. The only difference is that ad ids field with a large index range compared to age field.
2.2 Second, feature field has embedding of difference size. This is totally ok. But when you need to compute the FM second order term, the output embedding vector of different fields should be of the same size. In that case, you have to include another process (e.g., another dense layer) to project them to the same dimension.
2.3 Third, the feature field is itself a sequence of various size, e.g., text or click streams. This is totally ok too. In this case, you can have an encoder layer (e.g., CNN, RNN) to encode the sequence into a dense vector and use that as the field vector for DeepFM. For this, you can have a look at another project of mine: https://github.com/ChenglongChen/tensorflow-XNN
