### ISSUE TITLE
如何处理一个field中有多个特征为1的情况

### ISSUE THREAD

**Issue by xvlvzhu** [ChenglongChen/tensorflow-DeepFM#15]
数据集某一维特征中有多个值，那么onehot之后field中有多个列为1，deepfm怎么处理这样的情况呢？
(field_size ≠ input_size)

**Comment by LeiyuanMa** [comment]
同样在想这个问题~~期待回答~

**Comment by LeiyuanMa** [comment]
https://www.jianshu.com/p/4a7525c018b2，用这里的方法处理的时候，原来Xv: [[val1_1, val1_2, ...], [val2_1, val2_2, ...], ..., [vali_1, vali_2, ..., vali_j, ...], ...]，如果 feature field j有多值离散特征，vali_j是不是可以变成一个包含所有不重复特征的列表，就是这个链接里def SparseTensor中的table?

**Comment by unique94** [comment]
我的想法是：将能取多值离散特征的field单独划分出去，取平均得到该field的embedding;具体实现可以做padding进行batch训练;

**Comment by ChenglongChen** [comment]
@unique94 提到了其中的一种方法。我在另外一个 issue 也提到这种方式：https://github.com/ChenglongChen/tensorflow-DeepFM/issues/4。另外，如果这个 field 包含了序列数据，如文本，点击序列，可以使用 CNN/RNN 建模，见这里的回复：https://github.com/ChenglongChen/tensorflow-DeepFM/issues/7

**Comment by gaolinjie** [comment]
目前我按照 https://www.jianshu.com/p/4a7525c018b2 方法可以处理一个多值列了，但是如果有多个多值列怎么处理呢？我把多值列全部一起处理，但是由于每个列最终解析出的indices维度都不一样，tensorflow feed 给 placeholder的时候总是报 ValueError: setting an array element with a sequence。

比如一个batch就一个样本，然后有两个多值特征 [['a#c#e', 'f#c'], ['a#e', 'f#c']]。解析后的indices为[[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1]], [[0, 0], [0, 1], [1, 0], [1, 1]]]，把这个feed给placeholder就会报错，因为必须为array，而前面的indices中的两项维度不一样，分别为[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1]]和[[0, 0], [0, 1], [1, 0], [1, 1]]。

如果把 ['a#c#e', 'f#c']和 ['a#e', 'f#c']这两个多值特征分别手动处理就可以，这样我要是有10个多值特征，在代码里面就要写10次
