### ISSUE TITLE
Deep Component最开始的输入应该是最原始的Embedding结果？

### ISSUE THREAD

**Issue by gutouyu** [ChenglongChen/tensorflow-DeepFM#16]
https://github.com/ChenglongChen/tensorflow-DeepFM/blob/b0391f009c364c132ac927d39652519a473e7271/DeepFM.py#L106

这里是Deep Component中最原始的输入部分。但是此时的Embedding已经不在是最初的嵌入之后的结果了。此处的embedding乘上了输入x,目的应该是方便计算FM的二维组合特征部分。

在论文里，没有看到说Deep Component'的输入是什么，但是从给出的架构图上看，应该就是最原始的Embedding的结果。

希望得到解答，非常感谢~

**Comment by ChenglongChen** [comment]
1. deep component 的输入是 embedding 之后的 dense matrix。你提到的这个问题的核心点在于对 numerical feature（连续特征）的处理上面。
2. “此处的 embedding 乘上了输入x”，你提到的这点是对的，这里的 x 主要是为了处理 numerical 特征的幅值。
3. 原始论文中，关于 numerical 特征的处理是这样描述的，“and each continuous field is represented as the value itself, or a vector of one-hot encoding after discretization.” （Section 2）
4. 而在我的实现里面，为了简单，采用了另外一种方式，对于同一个 numerical feature（如 age），使用同一个 embedding vector * feature value。

**Comment by gutouyu** [comment]
好的，谢谢 我再研究下
