### ISSUE TITLE
Field-aware?

### ISSUE THREAD

**Issue by a-bharath** [ChenglongChen/tensorflow-DeepFM#24]
The Figure 4  in the DeepFM paper seems to indicate that the embeddings are "field-aware", but looking at the code it appears that field information is not used. Can you kindly confirm?

**Comment by ChenglongChen** [comment]
The filed is referred to feature field, it's not "field-aware". However, you can easily extend DeepFM to field-aware DeepFM. For example, considering feature filed i, you just use different embeddings of filed i (according to filed j) when computing the interaction terms between filed i and feature filed j.

**Comment by sudongxiang** [comment]
你好，老外。建议不要使用field-aware DeepFM，就像FFM和FM的比较一样，FFM有些时候效果会比FM还要差。 计算代价是一方面，另一方面违背了剃刀原理。
