### ISSUE TITLE
如何处理pre-trained embeddings?

### ISSUE THREAD

**Issue by shuangyangwang** [ChenglongChen/tensorflow-DeepFM#25]
如果我有一份训练好的向量想用于训练，但是不想被模型end-to-end修正。 那么应该如何操作？
感觉需要自己重新修改代码,如下：
```python
tf.get_variable(name = "pre_trained_embedding",
            shape = (ids_num,embedding_dimension),
            initializer = tf.constant_initializer(preTrainedEmbeddingData),
            trainable = False)
```

然后将这个embedding结果与其它的输入进行concat, 不知道这样思考对不对？

**Comment by ChenglongChen** [comment]
可以的。或者 tf.Variable(preTrainedEmbeddingData, trainable=False)

**Comment by sudongxiang** [comment]
最好将embedding加入到模型里面，一起训练，否则会有一定的损耗。例如IDs特征，可以pre训练用word2vec，但是效果不如直接将embedding加入到模型里面。
