### ISSUE TITLE
auc ????

### ISSUE THREAD

**Issue by wangbingok1118** [ChenglongChen/tensorflow-DeepFM#27]
![image](https://user-images.githubusercontent.com/22719977/42829610-7c5715e0-8a1c-11e8-90e4-be8a56c929ef.png)
why auc so low ?

**Comment by chenyanyin** [comment]
what's happended? I had the same problem

**Comment by chenyanyin** [comment]
> what's happended? I had the same problem

i see, metric is different.

**Comment by Jonny-Smith-GitHub** [comment]
The metrics is gini-norm.
