### ISSUE TITLE
请问下如果是针对多分类，target的格式应该是什么？

### ISSUE THREAD

**Issue by shuangyangwang** [ChenglongChen/tensorflow-DeepFM#28]
多分类情况下，我尝试了对label进行One-hot或者直接一维类别数组丢进去，程序都会报错！ 
请问下该如何进行定义target格式？

**Comment by WangliLin** [comment]
请问您解决了这个问题了吗

**Comment by shuangyangwang** [comment]
> 请问您解决了这个问题了吗

我自己重写了一份

**Comment by WangliLin** [comment]
> > 请问您解决了这个问题了吗
> 
> 我自己重写了一份

噢噢噢，能问下思路吗？^ ^或者贴个github链接，我star一波～哈哈

**Comment by sudongxiang** [comment]
sigmoid改为softmax，格式可以是【0 1 0】,注意，这是一条label，代表属于第二个类
