### ISSUE TITLE
feature field j has two or more nonzero values

### ISSUE THREAD

**Issue by sddi** [ChenglongChen/tensorflow-DeepFM#4]
Hi~
In my dataset if feature field j has two or more nonzero values how can i construct Xi and Xv vector ?

**Comment by ChenglongChen** [comment]
I was planning to change indi_j itself to be a list, which should handle the case that field j has more than one nonzero values, e.g., say field j is for the title of an ad (which contains some tokens/keys). However, I decided not to do this as I think it's more case/data/choice relevant how you feed your data to DeepFM. 
Event after embedding all those nonzero values, you still have to decide how to merge their embeddings to get the embedding of field j. For text, you can use fasttext like averaging or LSTM like final state. Or you can simply take every nonzero values as an individual field and let NN figure out how to merge them.
Hope it helps.

**Comment by sddi** [comment]
I got it~~~thank you very much @ChenglongChen
