### ISSUE TITLE
序列特征如何处理

### ISSUE THREAD

**Issue by liuyangvoid** [ChenglongChen/tensorflow-DeepFM#7]
你好
我有一些序列特征比如用户购买历史，用户搜索历史。
这些特征如何使用deepfm处理比较好？

**Comment by ChenglongChen** [comment]
针对 sequence input，譬如你提到的用户购买历史，用户搜索历史，又或者是文本输入，可以先使用一个 CNN/RNN 得到一个中间表示，然后再使用这个中间表示送到 deepfm。具体可以参考下我另外一个 project 写的代码：https://github.com/ChenglongChen/tensorflow-XNN，譬如这里https://github.com/ChenglongChen/tensorflow-XNN/blob/b72469db41dee811efa70d6943f37820bd5c8075/code/xnn.py#L312
