### ISSUE TITLE
concat层的输入

### ISSUE THREAD

**Issue by ningyuwhut** [ChenglongChen/tensorflow-DeepFM#9]
你好，请教一个问题。
我看代码里面concat层是把fm部分的一阶向量、二阶向量和dnn部分的最后一个隐层的向量连接在一块作为一个concat层，然后接一个全连接和sigmoid，得到最后的输出。但是原论文感觉是把fm的一阶部分、二阶部分和dnn部分的输出进行求和，然后在和的基础上使用sigmoid，得到最后的输出。

请问这么实现是有什么性能上的优势吗？
多谢了

**Comment by ChenglongChen** [comment]
没有作性能上面的考虑，concat 在一起，只是想让上层再根据数据学习出来如何把一阶，二阶和DNN融合在一起，相当于是对简单求和的一个泛化。
